Repository anitab-org/vms, pull requests merged in 2018-08, with the labels that each got.

#706 Validation of organization added
  vms/administrator/forms.py
  vms/administrator/models.py
  vms/administrator/tests/test_report.py
  vms/administrator/tests/test_settings.py
  vms/administrator/views.py
  vms/event/tests/test_services.py
  vms/event/tests/test_shiftSignUp.py
  vms/job/tests/test_services.py
  vms/organization/models.py
  vms/organization/services.py
  vms/organization/templates/organization/list.html
  vms/organization/tests/test_model.py
  vms/organization/tests/test_organization.py
  vms/organization/tests/test_services.py
  vms/organization/urls.py
  vms/organization/views.py
  vms/pom/locators/eventsPageLocators.py
  vms/pom/locators/volunteerProfilePageLocators.py
  vms/pom/pages/basePage.py
  vms/pom/pages/eventsPage.py
  vms/pom/pages/volunteerProfilePage.py
  vms/registration/views.py
  vms/shift/templates/shift/list_volunteers.html
  vms/shift/tests/test_manageVolunteerShift.py
  vms/shift/tests/test_services.py
  vms/shift/tests/test_shiftDetails.py
  vms/shift/tests/test_unit.py
  vms/shift/tests/test_viewVolunteerShift.py
  vms/shift/utils.py
  vms/vms/settings.py
  vms/vms/static/vms/css/style.css
  vms/vms/static/vms/js/hide-organization.js
  vms/volunteer/forms.py
  vms/volunteer/models.py
  vms/volunteer/services.py
  vms/volunteer/templates/volunteer/profile.html
  vms/volunteer/templates/volunteer/search.html
  vms/volunteer/tests/test_searchVolunteer.py
  vms/volunteer/tests/test_services.py
  vms/volunteer/tests/test_unit.py
  vms/volunteer/tests/test_volunteerProfile.py
  vms/volunteer/views.py
Labels: Category: Coding, Program: GSoC, Type: Enhancement

#808 Add model tests for administrator
  vms/administrator/tests/test_unit.py
  vms/shift/utils.py
Labels: Category: Coding, Program: GSoC, Type: Enhancement, category: testing

#756 Add logic for checking time in shift form
  vms/administrator/tests/test_settings.py
  vms/shift/forms.py
Labels: Category: Coding, Category: Quality Assurance, Difficulty: EASY, Program: GSoC, Type: Bug

#766 Add checks for extra field in model create
  vms/administrator/tests/test_formFields.py
  vms/event/tests/test_model.py
  vms/pom/locators/eventsPageLocators.py
  vms/pom/pages/eventsPage.py
  vms/shift/utils.py
  vms/volunteer/tests/test_unit.py
Labels: Category: Quality Assurance, Program: GSoC, Type: Enhancement, category: testing

#812 Add full clean checks for event, job and volunteer
  vms/event/tests/test_model.py
  vms/job/tests/test_model.py
  vms/volunteer/tests/test_unit.py
Labels: Category: Quality Assurance, Program: GSoC, Type: Enhancement, Type: Testing

#825 Report pdf
  requirements.txt
  vms/administrator/templates/administrator/confirm_report.html
  vms/administrator/templates/administrator/pdf.html
  vms/administrator/templates/administrator/reject_report.html
  vms/administrator/tests/test_report.py
  vms/administrator/views.py
  vms/vms/settings.py
Labels: Program: GSoC

#723 Added description field in events
  vms/event/forms.py
  vms/event/models.py
  vms/event/templates/event/create.html
  vms/event/templates/event/edit.html
  vms/event/tests/test_api.py
  vms/event/tests/test_event.py
  vms/event/tests/test_model.py
  vms/event/views.py
  vms/pom/locators/eventsPageLocators.py
  vms/pom/pages/eventsPage.py
  vms/shift/utils.py
Labels: Category: Coding, Program: GSoC

#838 Fix failing test in home app
  vms/home/tests/test_functional.py
Labels: Program: GSoC, Type: Bug

#801 Password change feature add
  vms/authentication/templates/registration/password_change_done.html
  vms/authentication/templates/registration/password_change_form.html
  vms/authentication/tests/test_login.py
  vms/authentication/urls.py
  vms/home/tests/test_functional.py
  vms/pom/locators/authenticationPageLocators.py
  vms/pom/locators/homePageLocators.py
  vms/pom/pageUrls.py
  vms/pom/pages/authenticationPage.py
  vms/pom/pages/homePage.py
  vms/vms/templates/vms/base.html
Labels: Program: GSoC

#799 Communicate with Portal api to create events
  vms/administrator/tests/test_settings.py
  vms/event/templates/event/create.html
  vms/event/urls.py
  vms/event/views.py
  vms/vms/urls.py
Labels: Program: GSoC

#826 Cities dropdown
  .travis.yml
  requirements.txt
  vms/administrator/forms.py
  vms/administrator/models.py
  vms/administrator/templates/administrator/edit.html
  vms/administrator/templates/administrator/profile.html
  vms/administrator/tests/test_report.py
  vms/administrator/tests/test_settings.py
  vms/administrator/views.py
  vms/event/forms.py
  vms/event/models.py
  vms/event/services.py
  vms/event/templates/event/create.html
  vms/event/templates/event/edit.html
  vms/event/tests/test_api.py
  vms/event/tests/test_searchEvent.py
  vms/event/tests/test_services.py
  vms/event/tests/test_shiftSignUp.py
  vms/event/views.py
  vms/job/services.py
  vms/job/tests/test_searchJob.py
  vms/job/tests/test_services.py
  vms/organization/tests/test_services.py
  vms/pom/locators/adminRegistrationPageLocators.py
  vms/pom/locators/volunteerProfilePageLocators.py
  vms/pom/locators/volunteerRegistrationPageLocators.py
  vms/pom/pages/adminRegistrationPage.py
  vms/pom/pages/volunteerProfilePage.py
  vms/pom/pages/volunteerRegistrationPage.py
  vms/registration/phone_validate.py
  vms/registration/templates/registration/city_dropdown_list_options.html
  vms/registration/templates/registration/signup_administrator.html
  vms/registration/templates/registration/signup_volunteer.html
  vms/registration/templates/registration/state_dropdown_list_options.html
  vms/registration/tests/test_functional_admin.py
  vms/registration/tests/test_functional_volunteer.py
  vms/registration/urls.py
  vms/registration/views.py
  vms/shift/models.py
  vms/shift/services.py
  vms/shift/tests/test_manageVolunteerShift.py
  vms/shift/tests/test_services.py
  vms/shift/tests/test_shiftDetails.py
  vms/shift/tests/test_unit.py
  vms/shift/tests/test_viewVolunteerShift.py
  vms/shift/utils.py
  vms/vms/static/vms/js/load_city.js
  vms/vms/static/vms/js/load_state.js
  vms/vms/templates/vms/base.html
  vms/volunteer/forms.py
  vms/volunteer/models.py
  vms/volunteer/services.py
  vms/volunteer/templates/volunteer/edit.html
  vms/volunteer/templates/volunteer/profile.html
  vms/volunteer/tests/test_searchVolunteer.py
  vms/volunteer/tests/test_services.py
  vms/volunteer/tests/test_unit.py
  vms/volunteer/tests/test_volunteerProfile.py
  vms/volunteer/views.py
Labels: Category: Coding, Program: GSoC

#782 Document automated testing in VMS
  aut_docs/Design_Document.md
  aut_docs/Documented_Failures.md
  aut_docs/Documented_failures.md
  aut_docs/Installation_Setup.md
  aut_docs/Setup.md
  aut_docs/Tutorial.md
  vms/administrator/tests/test_formFields.py
  vms/administrator/tests/test_report.py
  vms/administrator/tests/test_settings.py
  vms/event/tests/test_event.py
  vms/event/tests/test_model.py
  vms/event/tests/test_services.py
  vms/event/tests/test_shiftSignUp.py
  vms/job/tests/test_jobDetails.py
  vms/job/tests/test_model.py
  vms/organization/tests/test_model.py
  vms/organization/tests/test_organization.py
Labels: Category: Documentation/Training, Program: GSoC, Type: Enhancement

#841 UI updated
  vms/administrator/templates/administrator/edit.html
  vms/administrator/templates/administrator/profile.html
  vms/administrator/templates/administrator/report.html
  vms/authentication/templates/authentication/login.html
  vms/authentication/templates/registration/password_change_form.html
  vms/authentication/templates/registration/password_reset_done.html
  vms/authentication/templates/registration/password_reset_form.html
  vms/event/templates/event/edit.html
  vms/event/templates/event/list.html
  vms/event/templates/event/list_sign_up.html
  vms/home/templates/home/home.html
  vms/job/templates/job/edit.html
  vms/job/templates/job/list.html
  vms/job/templates/job/list_sign_up.html
  vms/organization/templates/organization/create.html
  vms/organization/templates/organization/edit.html
  vms/organization/templates/organization/list.html
  vms/pom/locators/eventSignUpPageLocators.py
  vms/pom/locators/manageShiftPageLocators.py
  vms/registration/templates/registration/signup_administrator.html
  vms/registration/templates/registration/signup_volunteer.html
  vms/shift/templates/shift/cancel_shift.html
  vms/shift/templates/shift/clear_hours.html
  vms/shift/templates/shift/edit.html
  vms/shift/templates/shift/hours_list.html
  vms/shift/templates/shift/list_jobs.html
  vms/shift/templates/shift/list_shifts.html
  vms/shift/templates/shift/list_volunteers.html
  vms/shift/templates/shift/manage_volunteer_shifts.html
  vms/shift/templates/shift/sign_up.html
  vms/shift/templates/shift/volunteer_search.html
  vms/shift/templates/shift/volunteer_shifts.html
  vms/vms/static/vms/css/style.css
  vms/vms/templates/vms/base.html
  vms/volunteer/templates/volunteer/edit.html
  vms/volunteer/templates/volunteer/profile.html
  vms/volunteer/templates/volunteer/report.html
  vms/volunteer/templates/volunteer/search.html
  vms/volunteer/templates/volunteer/view_history.html
Labels: Program: GSoC

#851 Organization name update in form
  vms/registration/views.py
Labels: Program: GSoC

#855 Hide textbox for resume link if resume file is uploaded in sign up form
  vms/registration/templates/registration/signup_volunteer.html
  vms/vms/static/vms/js/hide_resume_textbox.js
  vms/vms/templates/vms/base.html
Labels: Program: GSoC

#856 Past events not editable
  vms/event/templates/event/list.html
  vms/event/views.py
Labels: Program: GSoC

#850 Fix line ending issue in vms by converting CRLF to LF
  vms/shift/models.py
  vms/shift/services.py
  vms/shift/urls.py
  vms/volunteer/forms.py
  vms/volunteer/views.py
Labels: Category: Coding, Program: GSoC, Type: Enhancement

#860 Change admin email id on edit hours
  vms/shift/views.py
Labels: Program: GSoC

#864 Exception page for portal api in case of no connection
  vms/event/views.py
  vms/vms/templates/vms/no_connection.html
Labels: Program: GSoC

#863 Database doc updated
  docs/Database_Schema.md
Labels: Program: GSoC

#866 Modify usage of lists to dictionary
  vms/administrator/tests/test_formFields.py
  vms/administrator/tests/test_report.py
  vms/administrator/tests/test_settings.py
  vms/administrator/tests/test_unit.py
  vms/authentication/tests/test_login.py
  vms/event/tests/test_api.py
  vms/event/tests/test_event.py
  vms/event/tests/test_model.py
  vms/event/tests/test_searchEvent.py
  vms/event/tests/test_services.py
  vms/event/tests/test_shiftSignUp.py
  vms/home/tests/test_functional.py
  vms/job/tests/test_jobDetails.py
  vms/job/tests/test_model.py
  vms/job/tests/test_searchJob.py
  vms/job/tests/test_services.py
  vms/organization/tests/test_services.py
  vms/pom/pages/adminRegistrationPage.py
  vms/pom/pages/eventSignUpPage.py
  vms/pom/pages/eventsPage.py
  vms/pom/pages/homePage.py
  vms/pom/pages/volunteerProfilePage.py
  vms/pom/pages/volunteerRegistrationPage.py
  vms/registration/tests/test_functional_admin.py
  vms/registration/tests/test_functional_volunteer.py
  vms/shift/services.py
  vms/shift/tests/test_manageVolunteerShift.py
  vms/shift/tests/test_services.py
  vms/shift/tests/test_shiftDetails.py
  vms/shift/tests/test_shiftHours.py
  vms/shift/tests/test_unit.py
  vms/shift/tests/test_viewVolunteerShift.py
  vms/shift/utils.py
  vms/volunteer/tests/test_searchVolunteer.py
  vms/volunteer/tests/test_services.py
  vms/volunteer/tests/test_unit.py
  vms/volunteer/tests/test_volunteerProfile.py
Labels: Category: Quality Assurance, Difficulty: HARD, Program: GSoC

#859 Registration allowed with empty organization database
  vms/registration/views.py
Labels: Program: GSoC
