Repository anitab-org/vms, pull requests merged in 2018-06, with the labels that each got.

#695 Administrator Tests
  vms/administrator/tests/test_data.json
  vms/administrator/tests/test_formFields.py
  vms/administrator/tests/test_report.py
  vms/administrator/tests/test_selenium_working.py
  vms/administrator/tests/test_services.py
  vms/administrator/tests/test_settings.py
  vms/event/views.py
  vms/organization/models.py
  vms/organization/views.py
  vms/pom/locators/administratorReportPageLocators.py
  vms/pom/pages/administratorReportPage.py
  vms/pom/pages/basePage.py
  vms/pom/pages/eventsPage.py
  vms/shift/utils.py
Labels: Difficulty: MEDIUM, Program: GSoC, category: testing

#713 Gsoc18 infra
  .travis.yml
  requirements.txt
  vms/administrator/models.py
  vms/administrator/templates/administrator/edit.html
  vms/administrator/tests/test_data.json
  vms/administrator/tests/test_formFields.py
  vms/administrator/tests/test_report.py
  vms/administrator/tests/test_selenium_working.py
  vms/administrator/tests/test_services.py
  vms/administrator/tests/test_settings.py
  vms/administrator/urls.py
  vms/authentication/urls.py
  vms/event/urls.py
  vms/event/views.py
  vms/home/urls.py
  vms/job/templates/job/create.html
  vms/job/templates/job/edit.html
  vms/job/urls.py
  vms/manage.py
  vms/organization/models.py
  vms/organization/urls.py
  vms/organization/views.py
  vms/pom/locators/administratorReportPageLocators.py
  vms/pom/pages/adminRegistrationPage.py
  vms/pom/pages/administratorReportPage.py
  vms/pom/pages/authenticationPage.py
  vms/pom/pages/basePage.py
  vms/pom/pages/completedShiftsPage.py
  vms/pom/pages/eventSignUpPage.py
  vms/pom/pages/eventsPage.py
  vms/pom/pages/homePage.py
  vms/pom/pages/jobDetailsPage.py
  vms/pom/pages/manageShiftPage.py
  vms/pom/pages/shiftDetailsPage.py
  vms/pom/pages/upcomingShiftsPage.py
  vms/pom/pages/volunteerProfilePage.py
  vms/pom/pages/volunteerRegistrationPage.py
  vms/pom/pages/volunteerReportPage.py
  vms/pom/pages/volunteerSearchPage.py
  vms/registration/forms.py
  vms/registration/templates/registration/signup_administrator.html
  vms/registration/templates/registration/signup_volunteer.html
  vms/registration/urls.py
  vms/registration/views.py
  vms/shift/urls.py
  vms/shift/utils.py
  vms/vms/settings.py
  vms/vms/static/vms/js/hide-organization.js
  vms/vms/static/vms/js/hide_organization.js
  vms/vms/static/vms/js/timepicker.js
  vms/vms/static/vms/js/update-event-dates.js
  vms/vms/urls.py
  vms/volunteer/templates/volunteer/edit.html
  vms/volunteer/urls.py
  vms/volunteer/views.py
Labels: Program: GSoC

#712 login and logout class based view added
  vms/authentication/urls.py
Labels: Program: GSoC, Type: Enhancement

#707 Tests for Event app
  vms/event/models.py
  vms/event/tests/test_event.py
  vms/event/tests/test_model.py
  vms/event/tests/test_services.py
  vms/event/tests/test_shiftSignUp.py
  vms/event/tests/test_unit.py
  vms/pom/locators/eventsPageLocators.py
  vms/pom/pages/basePage.py
  vms/pom/pages/eventSignUpPage.py
  vms/pom/pages/eventsPage.py
  vms/shift/utils.py
Labels: Program: GSoC, Type: Testing, category: testing

#703 Tests for Job app
  vms/job/models.py
  vms/job/tests/test_jobDetails.py
  vms/job/tests/test_model.py
  vms/job/tests/test_services.py
  vms/pom/pages/basePage.py
  vms/pom/pages/jobDetailsPage.py
Labels: Program: GSoC, Type: Testing, category: testing

#710 Testing Organization app
  vms/administrator/tests/test_formFields.py
  vms/administrator/tests/test_report.py
  vms/administrator/tests/test_settings.py
  vms/organization/models.py
  vms/organization/tests/test_model.py
  vms/organization/tests/test_organization.py
  vms/pom/locators/eventsPageLocators.py
  vms/pom/pages/authenticationPage.py
  vms/pom/pages/basePage.py
  vms/pom/pages/eventsPage.py
  vms/pom/pages/homePage.py
Labels: Program: GSoC, Type: Testing, category: testing

#731 Fix error in a test of administrator app
  vms/administrator/tests/test_formFields.py
Labels: Category: Coding, Program: GSoC, Type: Bug, category: testing

#729 Fix error in a test in event app
  vms/event/tests/test_shiftSignUp.py
  vms/pom/locators/eventSignUpPageLocators.py
  vms/pom/pages/eventSignUpPage.py
Labels: Category: Coding, Program: GSoC, Type: Bug, category: testing

#749 Fix search event test by breaking it into 3 checks
  vms/event/tests/test_shiftSignUp.py
Labels: Priority: HIGH, Program: GSoC, Type: Testing, category: testing
