Repository anitab-org/vms, pull requests merged in 2018-05, with the labels that each got.

#681 Create Base module for Tests
  tests/__init__.py
  tests/administrator/__init__.py
  tests/administrator/test_working.py
  tests/authentication/__init__.py
  tests/authentication/test_working.py
  tests/event/__init__.py
  tests/event/test_working.py
  tests/home/__init__.py
  tests/home/test_working.py
  tests/job/__init__.py
  tests/job/test_working.py
  tests/organization/__init__.py
  tests/organization/test_working.py
  tests/pom/__init__.py
  tests/pom/test_working.py
  tests/registration/__init__.py
  tests/registration/test_working.py
  tests/shift/__init__.py
  tests/shift/test_working.py
  tests/volunteer/__init__.py
  tests/volunteer/test_working.py
Labels: Priority: HIGH, Program: GSoC, category: testing

#682 Integrate selenium
  .travis.yml
  aut_docs/Setup.md
  docs/Installation_Guide.md
  requirements.txt
  tests/__init__.py
  tests/administrator/__init__.py
  tests/authentication/__init__.py
  tests/authentication/test_working.py
  tests/event/__init__.py
  tests/event/test_working.py
  tests/home/__init__.py
  tests/home/test_working.py
  tests/job/__init__.py
  tests/job/test_working.py
  tests/organization/__init__.py
  tests/organization/test_working.py
  tests/pom/__init__.py
  tests/pom/test_working.py
  tests/registration/__init__.py
  tests/registration/test_working.py
  tests/shift/__init__.py
  tests/shift/test_working.py
  tests/volunteer/__init__.py
  tests/volunteer/test_working.py
  vms/administrator/tests/test_selenium_working.py
Labels: Difficulty: MEDIUM, Priority: HIGH, Program: GSoC, category: testing

#680 update javscript according to standards
  vms/administrator/templates/administrator/edit.html
  vms/job/templates/job/create.html
  vms/job/templates/job/edit.html
  vms/registration/templates/registration/signup_administrator.html
  vms/registration/templates/registration/signup_volunteer.html
  vms/vms/static/vms/js/hide-organization.js
  vms/vms/static/vms/js/hide_organization.js
  vms/vms/static/vms/js/timepicker.js
  vms/vms/static/vms/js/update-event-dates.js
  vms/volunteer/templates/volunteer/edit.html
Labels: Program: GSoC, Type: Maintenence

#690 Selenium Integration on travis.
  .travis.yml
  aut_docs/Setup.md
  docs/Installation_Guide.md
  requirements.txt
  vms/administrator/tests/test_selenium_working.py
Labels: Difficulty: EASY, Program: GSoC, category: testing

#678 Migrated to python3.6 and django 1.11
  .travis.yml
  requirements.txt
  vms/administrator/models.py
  vms/administrator/urls.py
  vms/authentication/urls.py
  vms/event/urls.py
  vms/home/urls.py
  vms/job/urls.py
  vms/manage.py
  vms/organization/urls.py
  vms/pom/pages/adminRegistrationPage.py
  vms/pom/pages/administratorReportPage.py
  vms/pom/pages/authenticationPage.py
  vms/pom/pages/completedShiftsPage.py
  vms/pom/pages/eventSignUpPage.py
  vms/pom/pages/eventsPage.py
  vms/pom/pages/homePage.py
  vms/pom/pages/jobDetailsPage.py
  vms/pom/pages/manageShiftPage.py
  vms/pom/pages/shiftDetailsPage.py
  vms/pom/pages/upcomingShiftsPage.py
  vms/pom/pages/volunteerProfilePage.py
  vms/pom/pages/volunteerRegistrationPage.py
  vms/pom/pages/volunteerReportPage.py
  vms/pom/pages/volunteerSearchPage.py
  vms/registration/forms.py
  vms/registration/urls.py
  vms/registration/views.py
  vms/shift/urls.py
  vms/vms/settings.py
  vms/vms/urls.py
  vms/volunteer/urls.py
  vms/volunteer/views.py
Labels: Category: Coding, Program: GSoC, Type: Enhancement
