Repository anitab-org/vms, pull requests merged in 2018-07, with the labels that each got.

#760 Replace nbsp by padding and alignment
  vms/administrator/templates/administrator/profile.html
  vms/administrator/templates/administrator/report.html
  vms/shift/templates/shift/sign_up.html
  vms/vms/static/vms/css/style.css
  vms/volunteer/templates/volunteer/profile.html
  vms/volunteer/templates/volunteer/report.html
Labels: Program: GSoC, Type: Maintenence

#795 Comment out retention tests of registration app
  vms/registration/tests/test_functional_admin.py
  vms/registration/tests/test_functional_volunteer.py
Labels: Category: Quality Assurance, Priority: HIGH, Program: GSoC, Type: Testing

#786 Gsoc 18 commits
  vms/administrator/tests/test_data.json
  vms/administrator/tests/test_formFields.py
  vms/administrator/tests/test_report.py
  vms/administrator/tests/test_selenium_working.py
  vms/administrator/tests/test_services.py
  vms/administrator/tests/test_settings.py
  vms/authentication/urls.py
  vms/event/models.py
  vms/event/tests/test_event.py
  vms/event/tests/test_model.py
  vms/event/tests/test_services.py
  vms/event/tests/test_shiftSignUp.py
  vms/event/tests/test_unit.py
  vms/event/views.py
  vms/job/models.py
  vms/job/tests/test_jobDetails.py
  vms/job/tests/test_model.py
  vms/job/tests/test_services.py
  vms/organization/models.py
  vms/organization/tests/test_model.py
  vms/organization/tests/test_organization.py
  vms/organization/views.py
  vms/pom/locators/administratorReportPageLocators.py
  vms/pom/locators/eventSignUpPageLocators.py
  vms/pom/locators/eventsPageLocators.py
  vms/pom/pages/adminRegistrationPage.py
  vms/pom/pages/administratorReportPage.py
  vms/pom/pages/authenticationPage.py
  vms/pom/pages/basePage.py
  vms/pom/pages/eventSignUpPage.py
  vms/pom/pages/eventsPage.py
  vms/pom/pages/homePage.py
  vms/pom/pages/jobDetailsPage.py
  vms/pom/pages/volunteerRegistrationPage.py
  vms/registration/tests/test_functional_admin.py
  vms/registration/tests/test_functional_volunteer.py
  vms/registration/tests/test_services.py
  vms/registration/tests/test_unit.py
  vms/registration/views.py
  vms/shift/utils.py
  vms/shift/views.py
Labels: Program: GSoC

#736 Testing volunteer app
  .travis.yml
  requirements.txt
  vms/pom/locators/volunteerProfilePageLocators.py
  vms/pom/pages/basePage.py
  vms/pom/pages/volunteerProfilePage.py
  vms/pom/pages/volunteerReportPage.py
  vms/pom/pages/volunteerSearchPage.py
  vms/volunteer/models.py
  vms/volunteer/tests/test_searchVolunteer.py
  vms/volunteer/tests/test_services.py
  vms/volunteer/tests/test_unit.py
  vms/volunteer/tests/test_volunteerProfile.py
  vms/volunteer/tests/test_volunteerReport.py
  vms/volunteer/views.py
Labels: Program: GSoC, Type: Testing, category: testing

#767 Bash script for configuring geckodriver
  .travis.yml
  setup-geckodriver.sh
Labels: Category: Coding, Program: GSoC, Type: Enhancement

#775 Add first_name and last_name for admin and volunteer
  vms/shift/utils.py
Labels: Program: GSoC, Type: Enhancement

#794 Remove debug print statements
  vms/registration/views.py
Labels: Category: Coding, Category: Quality Assurance, Difficulty: EASY, Program: GSoC, Type: Enhancement

#792 Log hours constraint added
  vms/shift/templates/shift/volunteer_shifts.html
Labels: Program: GSoC

#802 Password confirmation added in signup form for volunteer and administrator
  vms/pom/locators/adminRegistrationPageLocators.py
  vms/pom/locators/volunteerRegistrationPageLocators.py
  vms/pom/pages/adminRegistrationPage.py
  vms/pom/pages/volunteerRegistrationPage.py
  vms/registration/forms.py
  vms/registration/templates/registration/signup_administrator.html
  vms/registration/templates/registration/signup_volunteer.html
  vms/registration/tests/test_functional_admin.py
  vms/registration/tests/test_functional_volunteer.py
  vms/registration/utils.py
  vms/registration/views.py
Labels: Program: GSoC

#726 Tests for Shift App
  vms/pom/pages/basePage.py
  vms/pom/pages/completedShiftsPage.py
  vms/pom/pages/manageShiftPage.py
  vms/pom/pages/upcomingShiftsPage.py
  vms/shift/tests/test_manageVolunteerShift.py
  vms/shift/tests/test_services.py
  vms/shift/tests/test_shiftDetails.py
  vms/shift/tests/test_shiftHours.py
  vms/shift/tests/test_unit.py
  vms/shift/tests/test_viewVolunteerShift.py
  vms/shift/utils.py
  vms/shift/views.py
  vms/vms/utils.py
Labels: Program: GSoC, Type: Testing, category: testing

#810 Increase id value for all apps
  vms/event/tests/test_services.py
  vms/job/tests/test_services.py
  vms/organization/tests/test_services.py
  vms/volunteer/tests/test_services.py
Labels: Category: Quality Assurance, Program: GSoC, Type: Bug, category: testing

#777 Event search Form implemented in administration and volunteer side
  vms/administrator/tests/test_settings.py
  vms/event/forms.py
  vms/event/services.py
  vms/event/templates/event/list.html
  vms/event/templates/event/list_sign_up.html
  vms/event/tests/test_searchEvent.py
  vms/event/tests/test_services.py
  vms/event/tests/test_shiftSignUp.py
  vms/event/urls.py
  vms/event/views.py
  vms/pom/locators/eventSearchPageLocators.py
  vms/pom/locators/eventSignUpPageLocators.py
  vms/pom/locators/eventsPageLocators.py
  vms/pom/pages/eventSearchPage.py
  vms/pom/pages/eventSignUpPage.py
  vms/pom/pages/eventsPage.py
  vms/volunteer/templates/volunteer/search.html
Labels: Program: GSoC

#733 Testing Home app
  vms/home/tests/test_functional.py
  vms/home/tests/test_services.py
  vms/home/tests/test_unit.py
  vms/pom/locators/homePageLocators.py
  vms/pom/pages/homePage.py
Labels: Program: GSoC, Type: Testing, category: testing

#817 Fix failing tests
  vms/pom/locators/upcomingShiftsPageLocators.py
  vms/registration/tests/test_functional_volunteer.py
  vms/shift/tests/test_viewVolunteerShift.py
Labels: Program: GSoC, Type: Bug, Type: Testing

#716 Email Notification for volunteers
  vms/shift/templates/shift/cancel_email.txt
  vms/shift/templates/shift/sign_up_email.txt
  vms/shift/tests/test_manageVolunteerShift.py
  vms/shift/views.py
  vms/vms/settings.py
Labels: Category: Coding, Program: GSoC, Type: Enhancement

#811 Editing request option enabled for editing log hours
  vms/shift/admin.py
  vms/shift/forms.py
  vms/shift/models.py
  vms/shift/services.py
  vms/shift/templates/shift/hours_list.html
  vms/shift/templates/shift/request_admin.html
  vms/shift/tests/test_manageVolunteerShift.py
  vms/shift/tests/test_shiftHours.py
  vms/shift/tests/test_unit.py
  vms/shift/urls.py
  vms/shift/utils.py
  vms/shift/views.py
Labels: Program: GSoC

#788 Document POM tests
  vms/pom/tests/tests.md
Labels: Category: Documentation/Training, Program: GSoC, Type: Testing, category: testing

#790 Upcoming shifts filtered out
  vms/pom/pages/upcomingShiftsPage.py
  vms/shift/services.py
  vms/shift/tests/test_services.py
  vms/shift/tests/test_viewVolunteerShift.py
  vms/shift/utils.py
  vms/shift/views.py
Labels: Program: GSoC

#698 password forgot feature implemented
  vms/authentication/forms.py
  vms/authentication/templates/authentication/login.html
  vms/authentication/templates/registration/password_reset_complete.html
  vms/authentication/templates/registration/password_reset_confirm.html
  vms/authentication/templates/registration/password_reset_done.html
  vms/authentication/templates/registration/password_reset_email.html
  vms/authentication/templates/registration/password_reset_form.html
  vms/authentication/templates/registration/password_reset_subject.txt
  vms/authentication/tests/test_login.py
  vms/authentication/urls.py
  vms/authentication/views.py
  vms/pom/locators/authenticationPageLocators.py
  vms/pom/pageUrls.py
  vms/pom/pages/authenticationPage.py
  vms/vms/settings.py
Labels: Category: Coding, Program: GSoC, Type: Enhancement

#758 detail view added for events
  vms/event/templates/event/details.html
  vms/event/templates/event/list.html
  vms/event/tests/test_event.py
  vms/event/tests/test_searchEvent.py
  vms/event/urls.py
  vms/event/views.py
  vms/pom/locators/eventsPageLocators.py
  vms/pom/pages/eventsPage.py
Labels: Program: GSoC

#774 Event and job fields add in Volunteer search form
  vms/pom/locators/volunteerSearchPageLocators.py
  vms/pom/pages/volunteerSearchPage.py
  vms/volunteer/forms.py
  vms/volunteer/services.py
  vms/volunteer/templates/volunteer/search.html
  vms/volunteer/tests/test_searchVolunteer.py
  vms/volunteer/tests/test_services.py
  vms/volunteer/views.py
Labels: Program: GSoC

#824 Vola api implementation
  requirements.txt
  vms/event/tests/test_api.py
  vms/event/urls.py
  vms/event/views.py
  vms/vms/settings.py
Labels: Program: GSoC

#818 Execute automated tests in headless mode by default
  vms/administrator/tests/test_formFields.py
  vms/administrator/tests/test_report.py
  vms/administrator/tests/test_settings.py
  vms/authentication/tests/test_login.py
  vms/event/tests/test_event.py
  vms/event/tests/test_shiftSignUp.py
  vms/home/tests/test_functional.py
  vms/job/tests/test_jobDetails.py
  vms/organization/tests/test_organization.py
  vms/registration/tests/test_functional_admin.py
  vms/registration/tests/test_functional_volunteer.py
  vms/shift/tests/test_manageVolunteerShift.py
  vms/shift/tests/test_shiftDetails.py
  vms/shift/tests/test_shiftHours.py
  vms/shift/tests/test_viewVolunteerShift.py
  vms/volunteer/tests/test_searchVolunteer.py
  vms/volunteer/tests/test_volunteerProfile.py
  vms/volunteer/tests/test_volunteerReport.py
Labels: Category: Coding, Program: GSoC, Type: Enhancement, Type: Testing

#739 Reporting Functionality added
  vms/administrator/templates/administrator/report.html
  vms/administrator/templates/administrator/view_report.html
  vms/administrator/tests/test_report.py
  vms/administrator/urls.py
  vms/administrator/views.py
  vms/pom/locators/administratorReportPageLocators.py
  vms/pom/locators/volunteerSearchPageLocators.py
  vms/pom/pageUrls.py
  vms/pom/pages/administratorReportPage.py
  vms/pom/pages/volunteerReportPage.py
  vms/pom/pages/volunteerSearchPage.py
  vms/shift/admin.py
  vms/shift/models.py
  vms/shift/services.py
  vms/shift/tests/test_services.py
  vms/shift/tests/test_shiftHours.py
  vms/shift/tests/test_unit.py
  vms/shift/utils.py
  vms/volunteer/forms.py
  vms/volunteer/models.py
  vms/volunteer/templates/volunteer/report.html
  vms/volunteer/templates/volunteer/search.html
  vms/volunteer/templates/volunteer/view_history.html
  vms/volunteer/tests/test_searchVolunteer.py
  vms/volunteer/tests/test_volunteerReport.py
  vms/volunteer/urls.py
  vms/volunteer/views.py
Labels: Category: Coding, Program: GSoC, Type: Enhancement

#778 Job search admin
  vms/administrator/tests/test_settings.py
  vms/event/tests/test_shiftSignUp.py
  vms/job/forms.py
  vms/job/services.py
  vms/job/templates/job/list.html
  vms/job/templates/job/list_sign_up.html
  vms/job/tests/test_searchJob.py
  vms/job/tests/test_services.py
  vms/job/views.py
  vms/pom/locators/eventSignUpPageLocators.py
  vms/pom/locators/jobSearchPageLocators.py
  vms/pom/pages/eventSignUpPage.py
  vms/pom/pages/jobDetailsPage.py
  vms/pom/pages/jobSearchPage.py
  vms/shift/templates/shift/list_jobs.html
Labels: Program: GSoC
