Repository anitab-org/vms, pull requests merged in 2020-09, with the labels that each got.

#1066 docs: Added installation guide for RHEL/Feroda
  aut_docs/Installation_Setup.md
Labels: Status: Ready to Merge

#1075 UI: Changed the label of country field in volunteer signupform
  vms/registration/templates/registration/signup_volunteer.html
Labels: Status: Ready to Merge

#1060 Added separate templates for feature request and bug report
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUESTS.md
Labels: Status: Ready to Merge

#1093 type: docs added new commer link of zulip in README.md under commun…
  README.md
Labels: Status: Ready to Merge

#1091 Added Button in UI to link Zulip
  vms/home/templates/home/home.html
Labels: Status: Needs Review

#1064 docs: add a codecov badge (#1062)
  README.md
Labels: Status: Ready to Merge

#983 feat: add codecov
  .travis.yml
  requirements.txt
Labels: Status: Needs Testing

#1107 docs: added Python version Badge
  README.md
Labels: Status: Changes Requested

#1081 docs: add Installation guide for Windows OS
  aut_docs/Installation_Guide_WindowsOS.md
Labels: Status: Ready to Merge

#1069 docs: update file Code Of Conduct & all its respective references (#1047)
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: Status: Ready to Merge
